library(httr)

browseURL("https://www.canva.com/api/oauth/authorize?code_challenge_method=s256&response_type=code&client_id=OC-AZL89v-B4Rxg&scope=app:read%20app:write%20design:content:read%20design:meta:read%20design:content:write%20design:permission:read%20design:permission:write%20folder:read%20folder:write%20folder:permission:read%20folder:permission:write%20asset:read%20asset:write%20comment:read%20comment:write%20brandtemplate:meta:read%20brandtemplate:content:read%20profile:read&code_challenge=m2_F7ndm2WhkD3wC8wSwcxa7uh_DSQZLcqMnStni5K4")

# Correctly format headers
headers <- c(
  'Authorization' = 'Bearer eyJraWQiOiJlODZiMTIwMy1iMWY1LTQ4N2MtYjBiOS0yN2U0MmI2ZjMzZDkiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJOOHBKQldDNlJKckZrQlNzY2VKZXJ3IiwiY2xpZW50X2lkIjoiT0MtQVpMODl2LUI0UnhnIiwiYXVkIjoiaHR0cHM6Ly93d3cuY2FudmEuY29tIiwiaWF0IjoxNzMyNzQ0MjY3LCJuYmYiOjE3MzI3NDQyNjcsImV4cCI6MTczMjc0NDg2NywiYnVuZGxlcyI6WyJBRkZJIiwiUEFJRCJdLCJ0aWVyIjoicGFpZCIsInJvbGVzIjoid0tWaWpuck9IWm5fYlNiclhyRzdaNlBpQzhvRFczNnl3UmRNU2lRUWVwWDJrc1Npdkd1QTlWdUdESUs4NWpIc2JPU0hWUSIsImxvY2FsZSI6InNqTVJvQVM0d0NVNWVWWC1CbHFjcTdtNUlJUXNYUkl3cjlQVnlhWEJmVFRZSlJoU0pSSGFFblJIWVYtVXRQUTBZUWlsbGciLCJzY29wZXMiOlsiYXBwOnJlYWQiLCJhcHA6d3JpdGUiLCJkZXNpZ246Y29udGVudDpyZWFkIiwiZGVzaWduOm1ldGE6cmVhZCIsImRlc2lnbjpjb250ZW50OndyaXRlIiwiZGVzaWduOnBlcm1pc3Npb246cmVhZCIsImRlc2lnbjpwZXJtaXNzaW9uOndyaXRlIiwiZm9sZGVyOnJlYWQiLCJmb2xkZXI6d3JpdGUiLCJmb2xkZXI6cGVybWlzc2lvbjpyZWFkIiwiZm9sZGVyOnBlcm1pc3Npb246d3JpdGUiLCJhc3NldDpyZWFkIiwiYXNzZXQ6d3JpdGUiLCJjb21tZW50OnJlYWQiLCJjb21tZW50OndyaXRlIiwiYnJhbmR0ZW1wbGF0ZTptZXRhOnJlYWQiLCJicmFuZHRlbXBsYXRlOmNvbnRlbnQ6cmVhZCIsInByb2ZpbGU6cmVhZCJdLCJzdWIiOiJvVVZ3bnFUTjRETmtkMGgyQkNUZDZFIiwiYnJhbmQiOiJvQlZ3bjJZazZneGFYSl9jdHh5QWg0Iiwib3JnYW5pemF0aW9uIjpudWxsLCJwa2NlIjoic1hyc1NORzRseC1WVm1Vby1RbkRYRmplaE16V0VBM0tqOWhMS0trcC1mdVFlX2RxbEl6LWhYNkpycjZ5NFR2blRNVGMyaVppaXB4Qmc2WkxMdGswbi16NkRYdkk4VzYtOHBvdU1jd3V1QW9ETFpiSCJ9.woNJ7ANeyUcfRmua35j8LXZ0NxzrZeulOsTrHPWMaUWPxE-HmPQNYWZeeECFSKQwKxWlAZ54pi6HDzGPEoJgOQies3tg88BIR95sqmJBsmsbzxoSY7lq2DfIFVYIZ5syhlNMIl80moLFrIaKf7n9LiK6Hvwbyamw2clu8VThu3xzeNmwt05xeVn3AzZUVOlfXjzNuilZJtaESRZf5OzPzeX9RjncZpVY8PZEHZJREoq3bamScWVeQqThN6eE4TdArefBaBkrTrcJpLTeJeehse-GjTvnpsuuG64TFwx7aCDJ2n844XG015HrywEAImPyozyuE9eGmKmX04ztfx1KiA'
)

# Make the request with the correct headers
res <- VERB("GET", url = "https://api.canva.com/rest/v1/brand-templates/DAGUVydZ3L4/dataset", add_headers(.headers = headers))

# Output the content
cat(content(res, 'text')) 

